services:
  vault:
    image: hashicorp/vault:1.20
    container_name: devnet_vault
    restart: always
    ports:
      - "${VAULT_PORT:-8200}:8200"
    environment:
      - VAULT_API_ADDR=https://0.0.0.0:8200
    volumes:
      - ./logs:/vault/logs
      - ./file:/vault/file
      - ./config:/vault/config
      - ./certs:/vault/certs
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
