[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req

[req_distinguished_name]
countryName                 = Country Name (2 letter code)
countryName_default         = US
stateOrProvinceName         = State or Province Name (full name)
stateOrProvinceName_default = State
localityName                = Name (eg, city)
localityName_default        = City
organizationName            = Organization Name (eg, company)
organizationName_default    = HORNLAB01
commonName                  = Common Name
commonName_max              = 64
commonName_default          = localhost # TODO replace with the FQDN/IP of HORNLAB01

[v3_req]
subjectAltName = @alt_names

[alt_names]
IP.1 = 127.0.0.1 # TODO replace with HORNLAB01's real IP that the Cat8000V will dial out to
